# Generated by Django 4.1 on 2022-08-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rdisl', '0002_alter_slider_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('images', models.ImageField(blank=True, upload_to='images')),
                ('slug', models.SlugField(unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_our_services',
            },
        ),
    ]
