# Generated by Django 4.1 on 2022-08-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rdisl', '0003_ourservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_gallery_category',
            },
        ),
        migrations.RenameField(
            model_name='ourservices',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ourservices',
            old_name='update_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='pub_date',
            new_name='updated_at',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rdisl.gallery_category')),
            ],
            options={
                'db_table': 'tbl_gallery',
            },
        ),
    ]
