# Generated by Django 4.1 on 2022-08-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rdisl', '0004_gallery_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery_Category',
            new_name='GalleryCategory',
        ),
    ]
