# Generated by Django 4.1 on 2022-08-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rdisl', '0005_rename_gallery_category_gallerycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_client',
            },
        ),
    ]
